### ISSUE TITLE
[Feature Request] Add papers using URL path to PDF

### ISSUE THREAD

**Issue by x-lad** [Future-Scholars/paperlib-entry-scrape-extension#1]
I want to use the URL through the command and not the ID to download a PDF and import it to paperlib.

Even though there is an extension, using the extension is less desirable. The motivation to not use the extension is:
too many extensions cause the browser to be bloated. Additionally, if a hosted version of paperlib will be released, then I will have to download the extension on every environment I use.

Even though one can use the \import-from command with an ID, it is less desirable. The motivation to not use the ID:
Sometimes, it's not from Arxiv, and you can not swiftly extract an ID or DOI (if it's even possible). Furthermore, sometimes, I add lecture notes or papers under review from the open review, and then they might not have these attributes.

The emphasis of this feature is to receive a link with a PDF (only), and add it to paperlib.
This should "automate" the manual task of
1 finding a pdf
2 downloading it
3 dragging it to paperlib

**Comment by GeoffreyChen777** [comment]
Thanks, will investigate.

**Comment by GeoffreyChen777** [comment]
Implemented, please upgrade this extension.

Now you can import a paper from its URL such as `\import-from https://arxiv.org/abs/2407.21783`

However, for some webpages protected by reCAPTCHA or similar, it's not guaranteed you can successfully import since accessing the webpage content out of a real browser is hard. Thus we recommend using the browser extension.
